-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1WjtoptTwMbnx8j9
/XpdYEHczZmwVA2z9KMpeVzW3bCgCgYIKoZIzj0DAQehRANCAASS7DJgyj3a06vy
+CuTlSeXUiNglXjOHBrsI0p6OpOB1j9+zoby4KjnARuBjORw70VDXROznXoKif8e
UnyH12HS
-----END PRIVATE KEY-----